@extends('layout.app')
@section('appContents')
    <h1 class="p-2 m-2">Home</h1>
    <p class="p-2 m-2">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vero optio dolorum aliquam. Voluptatem velit, delectus sapiente dolorem repudiandae amet nesciunt facere! Vero atque corporis, asperiores fugit enim et fugiat saepe nostrum? Possimus, voluptatem a? Impedit, repellendus perspiciatis. Architecto, sed quo nihil eos sunt incidunt facilis molestias sit? Molestiae, minus autem. Ex commodi odit aperiam porro molestiae officia sequi quasi! Aspernatur, cupiditate. Itaque quibusdam minus accusamus illo rem possimus voluptate magni reprehenderit, illum libero, id magnam fugiat. Cupiditate, itaque. Nisi nemo reiciendis consectetur minus illo ipsum ab tempore sunt esse rerum dignissimos nam saepe tenetur, consequatur expedita laboriosam eum perferendis accusamus.</p>
    <p class="p-2 m-2">Fuga dicta doloremque itaque non doloribus laboriosam tempora necessitatibus assumenda corporis, labore, distinctio odit iste in accusantium? Eligendi iste ad nihil assumenda quae esse et ipsa recusandae inventore repellat in ullam consectetur ea nesciunt pariatur quam alias dicta illo porro sit itaque sunt, nulla doloremque. Quas aliquam voluptatem illo velit nesciunt quos illum fugit unde alias obcaecati neque eius saepe, nobis, labore sit facere incidunt. Voluptate quod tempora magni laudantium. Laboriosam nostrum perspiciatis animi quasi aut quo officiis laudantium sunt. Iusto optio vel distinctio unde fuga, eum eius molestias animi quis consectetur quos adipisci nobis alias modi et sequi sunt?</p>
    <p class="p-2 m-2">Explicabo, quis eaque quia sit minus temporibus aperiam accusamus distinctio esse inventore id iure quas suscipit dolorum. Eveniet omnis, quo maxime velit voluptatibus ipsum consectetur natus illum obcaecati ex tempora itaque totam quasi sit explicabo, sed repellendus porro inventore nisi odit harum? Excepturi suscipit maiores voluptas aliquid cumque asperiores perspiciatis minima laudantium error nihil et quidem possimus ullam ipsam molestiae neque nobis vitae deleniti accusantium non, fugit tempore adipisci at? Assumenda nulla error consequatur, at distinctio quia iusto doloribus id, perferendis ducimus voluptatum quam quis commodi non consectetur explicabo ut animi cum architecto cupiditate. Excepturi ad asperiores maxime suscipit ipsam.</p>
    <p class="p-2 m-2">Blanditiis voluptatum aspernatur qui, quasi aperiam officia neque, quas animi recusandae ducimus architecto eum! Itaque perspiciatis recusandae, libero sint aspernatur, ut ullam cum accusamus incidunt deserunt sit tempore nam dignissimos repellat labore vero sapiente ipsa magnam maxime reiciendis corporis possimus placeat qui aliquid. Maiores necessitatibus voluptate repudiandae vel odio possimus laboriosam voluptatum, distinctio minima illum magni quia sed inventore officia beatae accusamus maxime sint obcaecati nulla ipsam incidunt suscipit dolore! Cupiditate dignissimos temporibus deleniti tenetur eligendi minus natus ullam blanditiis quis consequuntur, soluta ab eius perspiciatis totam, dolorem quidem numquam quasi tempore explicabo cumque animi. Provident dolore porro quos consequuntur.</p>
    <p class="p-2 m-2">Modi minus sed soluta a laborum sit doloremque, nemo sint explicabo magni dicta maiores, molestias aperiam! Animi porro a, harum corporis, quisquam aliquam aut provident quam molestiae beatae fuga ullam quos quasi recusandae eius blanditiis voluptatem illum optio dolorem velit. Natus error possimus nostrum numquam sapiente atque distinctio reiciendis tenetur molestias dignissimos, vitae omnis tempore sequi, iste praesentium est expedita labore consequuntur eveniet veniam asperiores animi ab deleniti? Maiores, molestiae. Dolor, numquam tenetur magnam hic aspernatur reprehenderit obcaecati modi deserunt sapiente soluta? Alias impedit consequuntur, dicta, minus architecto nostrum qui sunt vero, distinctio beatae omnis harum aliquid animi. Libero, numquam?</p>
@endsection

